require: rubocop-rspec

Rails:
    Enabled: true
# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
    Max: 100
Metrics/ClassLength:
    Enabled: false
# Check with yard instead.
Documentation:
    Enabled: false
RSpec/NestedGroups:
    Enabled: false
