#!/bin/bash
SESSION="bo $PWD"
cd '/home/guilherme/repos/be/trunk/backoffice2'
tmux -2 new-session -d -s "$SESSION"

tmux new-window -t "$SESSION" -a -n bo-server 
tmux split-window -h
tmux select-pane -t 0
tmux send-keys -t 0 C-z 'npm run start' Enter
tmux split-window -v
tmux send-keys -t 1 C-z 'npm run watch-css' Enter
tmux select-pane -t 2
tmux split-window -v

tmux new-window -t "$SESSION" -a -n general-purpose 
tmux split-window -h
tmux select-pane -t 0
